import "@fortawesome/fontawesome-svg-core/styles.css"
import { config } from "@fortawesome/fontawesome-svg-core"; 
config.autoAddCss = false;

import type { Metadata } from "next";
import { Poppins } from 'next/font/google'
import { Navbar } from "@/components";
import "./globals.css";

import { cn } from "@/helpers/cn";

const poppins = Poppins({
  style: 'normal',
  weight: '400',
  subsets: ['latin'],
}) 

export const metadata: Metadata = {
  title: "Games App",
  description: "Generated by Juciley Costa WEB3",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("bg-slate-900 text-white", poppins.className)}>
        <div className="flex w-full">
          <Navbar />  
          
          {children} 
        </div>
   
      </body>
    </html>
  );
}
