import "@fortawesome/fontawesome-svg-core/styles.css"
import { config } from "@fortawesome/fontawesome-svg-core"; 
config.autoAddCss = false;

import type { Metadata } from "next";
import { Poppins } from 'next/font/google'
import { Navbar } from "@/components";
import "./globals.css";

import { cn } from "@/helpers/cn";
import { getSession } from "@/helpers/session";

const poppins = Poppins({
  style: 'normal',
  weight: '400',
  subsets: ['latin'],
}) 

export const metadata: Metadata = {
  title: "Games App",
  description: "Generated by Juciley Costa WEB3",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const user = await getSession();
  
  return (
    <html lang="en">
      <body className={cn("bg-slate-890 text-slate-300", poppins.className)}>
        <div className="flex w-full">
          <Navbar user={user} />            
          {children} 
        </div>   
      </body>
    </html>
  );
}
